import React from 'react';
import './common.css';

const Tsunami = () => {
    return (
        <div className="disaster-container">
            <header className="disaster-header">
                <h1>Tsunami</h1>
            </header>

            <section className="disaster-section">
                <div className="disaster-image">
                    <img src="https://img.freepik.com/free-photo/natural-disaster-concept-with-flood_23-2150385378.jpg?t=st=1723339833~exp=1723343433~hmac=88b4319ad964314b099324b02a6b31faf043b0d66ea7e0b3cd863dceb5df6151&w=1060" alt="Tsunami" />
                </div>
                <div className="disaster-content">
                    <h2>What is a Tsunami?</h2>
                    <p>
                        A tsunami is a series of large ocean waves caused by the sudden displacement of water, usually due to seismic activities such as underwater earthquakes, volcanic eruptions, or landslides. Unlike regular ocean waves, tsunamis are generated by vertical movements of the seafloor and can travel across entire ocean basins with great speed and energy.
                        <br /><br />
                        Tsunamis are often triggered by tectonic plate movements in the Earth's crust, particularly in regions where plates converge or diverge. When these movements cause an underwater earthquake, they can displace large volumes of water, generating powerful waves that radiate outward from the epicenter. In addition to earthquakes, underwater volcanic eruptions and landslides can also cause tsunamis by rapidly displacing water.
                        <br /><br />
                        Tsunamis can be extremely destructive when they make landfall. As they approach shallow waters near the coast, their speed decreases, but their height increases significantly, leading to towering waves that can inundate coastal areas. The impact of a tsunami can cause widespread flooding, damage to infrastructure, and loss of life. The initial wave may be followed by additional waves, known as a tsunami wave train, which can continue to impact coastal areas for several hours.
                        <br /><br />
                        Effective tsunami preparedness involves early detection, timely warnings, and community awareness. Tsunami warning systems use seismographic data and ocean buoys to detect and monitor potential tsunami-generating events. When a tsunami warning is issued, it is crucial for individuals and communities to evacuate to higher ground and follow safety instructions to minimize the risk of harm.
                    </p>
                </div>
            </section>

            <section className="disaster-section">
                <div className="disaster-content">
                    <h2>Signs of a Tsunami</h2>
                    <ul>
                        <li>Sudden and unusual withdrawal of water from the shore</li>
                        <li>Strong and rapid earthquake shaking</li>
                        <li>Unusual sea sounds such as roaring or loud explosions</li>
                        <li>Sudden rise in sea level or appearance of large waves</li>
                        <li>Reports of tsunami warnings or alerts from authorities</li>
                        <li>Rapid and significant changes in sea surface temperature</li>
                        <li>Large-scale underwater landslides or volcanic eruptions</li>
                        <li>Observations of water receding unusually far from the shore</li>
                        <li>High waves or surges followed by a rapid retreat of the ocean</li>
                        <li>Reports of distant tsunamis affecting other coastal areas</li>
                    </ul>
                </div>
            </section>

            <section className="disaster-section">
                <div className="disaster-content">
                    <h2>How to Act During a Tsunami</h2>
                    <p>
                        Tsunamis can strike with little warning, making it essential to act quickly and follow safety procedures to protect yourself and others. Here are key actions to take during a tsunami:
                        <br /><br />
                        If you are in a coastal area and feel a strong earthquake or receive a tsunami warning, immediately move to higher ground. Tsunamis can arrive within minutes of an earthquake, so swift evacuation is crucial. Avoid staying in low-lying areas or near the shore, as these are most vulnerable to tsunami impacts.
                        <br /><br />
                        If you notice the ocean receding dramatically or hear unusual sounds, it is likely a tsunami is imminent. Move away from the beach and head to a designated tsunami evacuation area or higher ground as quickly as possible. Avoid using vehicles, as traffic congestion can slow down evacuation efforts.
                        <br /><br />
                        If you are in a tsunami-prone area and cannot evacuate in time, find a sturdy building and move to the upper floors. Stay indoors and away from windows to avoid injury from debris and water. If you are caught in the water, try to grab onto anything that floats and avoid swimming against the current.
                        <br /><br />
                        After the initial tsunami wave, be cautious of subsequent waves, as they can continue to hit the shore for several hours. Follow official instructions and wait for the "all clear" signal from authorities before returning to affected areas. Be aware of potential hazards such as contaminated water, damaged infrastructure, and debris.
                        <br /><br />
                        Community preparedness is essential for effective tsunami response. Participate in local drills, familiarize yourself with evacuation routes, and stay informed about tsunami risks and warning systems. Educate others about the importance of tsunami preparedness and encourage them to take appropriate actions to stay safe.
                    </p>
                    <h3>Advisory Steps:</h3>
                    <ul className="advisory-steps">
                        <li>Move to higher ground immediately if you feel a strong earthquake.</li>
                        <li>Avoid staying in low-lying coastal areas.</li>
                        <li>Follow tsunami warnings and evacuation orders from authorities.</li>
                        <li>Find a sturdy building or higher floor if evacuation is not possible.</li>
                        <li>Stay away from the shore and avoid swimming in tsunami-affected waters.</li>
                        <li>Be cautious of aftershocks and subsequent waves.</li>
                        <li>Wait for official "all clear" signals before returning to affected areas.</li>
                        <li>Participate in community preparedness programs and drills.</li>
                        <li>Educate others about tsunami risks and safety measures.</li>
                        <li>Monitor local news and official channels for updates and instructions.</li>
                    </ul>
                </div>
            </section>

            <section className="helpline-info">
                <h3>Government Helplines</h3>
                <p>India Disaster Management Helpline: 1078</p>
                <p>National Disaster Response Force (NDRF): 011-24363260</p>
                <p>State Disaster Management Authority (Contact for specific state numbers)</p>
            </section>
        </div>
    );
};

export default Tsunami;
